use dbphp7;

CREATE TABLE TB_USUARIOS (
IDUSUARIO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
DESLOGIN VARCHAR(64) NOT NULL,
DESSENHA VARCHAR(256) NOT NULL, 
DTCADASTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO TB_USUARIOS (DESLOGIN,DESSENHA)
VALUES ('root','123456');

SELECT * FROM TB_USUARIOS